[package]
name = "blockchain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "*"
hex = "*"
ed25519 = "1.2.0"
rand = "0.7.0"
ed25519-dalek="1.0.1"
time = "0.1"