[package]
name = "blockchain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "*"
hex = "*"
rand = "0.8.0"
rand_core = "0.6.3"
ed25519-dalek = "1.0.1"
ed25519 = "1.2.0"